[versions]
dokka = "1.9.20"
kotlin = "2.0.21"
kover = "0.8.3"
knit = "0.5.0"
spotless="6.25.0"
publish="0.30.0"
json="1.7.3"
okio="3.9.1"
kasechange="1.4.1"
ktor="2.3.12"
kotlinpoet="1.18.1"
agp = "8.6.1"
test-compile = "0.5.1"

[libraries]
gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
kasechange = { module = "net.pearx.kasechange:kasechange", version.ref = "kasechange" }
ktor-client = { module= "io.ktor:ktor-client-core", version.ref="ktor" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref="kotlinpoet" }
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
test-compile = { module = "dev.zacsweers.kctfork:core", version.ref = "test-compile"}

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
assert = { id = "org.jetbrains.kotlin.plugin.power-assert",  version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
knit = { id = "org.jetbrains.kotlinx.knit", version.ref = "knit" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
publish = { id = "com.vanniktech.maven.publish", version.ref="publish" }
